# This is my input
number_of_iterations: 1       # something to write
# parquet_filename: 2361_1730_1781_hybrid.parquet   # this is the file name
# parquet_filename_check: 2361_1730_1781_hybrid.parquet

seed: 42
core: 0
log_file: tree_maker.log
